### ISSUE TITLE
La Lezione 7 ha un problema con i link!

### ISSUE THREAD

**Issue by LabSIS1234** [pablitocalvo/LAB_SIS#1]
Tutti i cicli portano allo stesso es.
Questo qui: https://github.com/pablitocalvo/LAB_SIS/blob/master/ASSEMBLER/ciclo_01.asm

**Comment by pablitocalvo** [comment]
Grazie ho corretto ....
dopo tanto troubleshooting ...
la prossima vediamo come non solo sottoporre un problema ma anche di proporre una soluzione...
ottimo lavoro di approfondimento !
